### ISSUE TITLE
Please tag version 3.3.0

### ISSUE THREAD

**Issue by ibotty** [Uberspace/paternoster#49]
To make it easier to find.

**Comment by luto** [comment]
done, thanks

**Comment by ibotty** [comment]
Thank you for tagging.  I just noticed, that it's not yet published on pypi.  That's an oversight, right?  I intend to package for fedora and will source from github, so I don't neccessarily care though.

**Comment by luto** [comment]
There aren't any functional changes in v3.3.0. I am not sure why I even tagged it back then. https://github.com/Uberspace/paternoster/compare/v3.2.1...v3.3.0
